// Direct3D 11 backend for rf::gfx and rf::draw.
//
// One device, one swap chain, one shader pair, one dynamic vertex buffer.
// Everything the game draws becomes triangles in that buffer, flushed with a
// single Draw() whenever the texture changes or the buffer fills. Textures
// and render targets live in fixed tables. The same code, minus the desktop
// swap chain, is what runs on the console under the GDK.
#include "rf/Draw.h"
#include "rf/Graphics.h"

#include <array>
#include <cassert>
#include <cmath>
#include <cstring>

#include <windows.h>
#include <d3d11.h>
#include <dxgi1_3.h>
#include <wrl/client.h>

#include "Sprite_ps.h"   // kSpritePS: generated by fxc at build time (CMakeLists.txt)
#include "Sprite_vs.h"   // kSpriteVS
#include "rf/Log.h"
#include "rf/Platform.h"

using Microsoft::WRL::ComPtr;

namespace rf {

namespace {

struct Vertex {
    float        x, y;
    float        u, v;
    unsigned int rgba;   // R8G8B8A8_UNORM: r in the low byte
};

constexpr int   kMaxVertices    = 6 * 4096;   // 4096 quads per flush
constexpr int   kCircleSegments = 36;
constexpr float kPi             = 3.14159265f;
constexpr int   kFilters        = 3;
constexpr int   kWraps          = 2;

struct TextureSlot {
    ComPtr<ID3D11Texture2D>          tex;
    ComPtr<ID3D11ShaderResourceView> srv;
    int         w {0};
    int         h {0};
    gfx::Filter filter {gfx::Filter::Point};
    gfx::Wrap   wrap {gfx::Wrap::Clamp};
    bool        used {false};
    bool        isTarget {false};
};

struct TargetSlot {
    ComPtr<ID3D11RenderTargetView> rtv;
    TextureId texture;
    int       w {0};
    int       h {0};
    bool      used {false};
};

struct State {
    ComPtr<ID3D11Device>           device;
    ComPtr<ID3D11DeviceContext>    ctx;
    ComPtr<IDXGISwapChain1>        swap;
    ComPtr<ID3D11RenderTargetView> backRtv;
    int backW {0};
    int backH {0};

    ComPtr<ID3D11VertexShader>     vs;
    ComPtr<ID3D11PixelShader>      ps;
    ComPtr<ID3D11InputLayout>      layout;
    ComPtr<ID3D11Buffer>           vbuf;
    ComPtr<ID3D11Buffer>           cbuf;
    ComPtr<ID3D11BlendState>       blend;
    ComPtr<ID3D11RasterizerState>  raster;
    std::array<std::array<ComPtr<ID3D11SamplerState>, kWraps>, kFilters> samplers;

    std::array<TextureSlot, gfx::kMaxTextures> textures;
    std::array<TargetSlot, gfx::kMaxTargets>   targets;
    TextureId white;

    std::array<Vertex, kMaxVertices> verts;
    int       vertCount {0};
    TextureId batchTex;

    ID3D11RenderTargetView* curRtv {nullptr};   // non-owning: backRtv or a target's rtv
    int      curW {0};
    int      curH {0};
    TargetId boundTarget;
    Vector2  viewOffset {0.0f, 0.0f};
    float    viewZoom {1.0f};
    bool     ready {false};
};

State g;

// ---- helpers ---------------------------------------------------------------

unsigned int Pack(Color c)
{
    return static_cast<unsigned int>(c.r) | (static_cast<unsigned int>(c.g) << 8) |
           (static_cast<unsigned int>(c.b) << 16) | (static_cast<unsigned int>(c.a) << 24);
}

bool ValidTexture(TextureId id)
{
    return id.index >= 0 && id.index < gfx::kMaxTextures && g.textures[static_cast<size_t>(id.index)].used;
}

bool ValidTarget(TargetId id)
{
    return id.index >= 0 && id.index < gfx::kMaxTargets && g.targets[static_cast<size_t>(id.index)].used;
}

TextureSlot& Tex(TextureId id)
{
    assert(ValidTexture(id));
    return g.textures[static_cast<size_t>(id.index)];
}

bool CreateBackBufferView()
{
    ComPtr<ID3D11Texture2D> back;
    HRESULT hr = g.swap->GetBuffer(0, IID_PPV_ARGS(&back));
    if (FAILED(hr)) { log::Write(log::Level::Error, "GFX: GetBuffer failed (0x%08lx)", hr); return false; }
    hr = g.device->CreateRenderTargetView(back.Get(), nullptr, &g.backRtv);
    if (FAILED(hr)) { log::Write(log::Level::Error, "GFX: CreateRenderTargetView failed (0x%08lx)", hr); return false; }
    return true;
}

bool CreatePipeline()
{
    // Shader bytecode was produced by fxc at build time; nothing is compiled here.
    HRESULT hr = g.device->CreateVertexShader(kSpriteVS, sizeof(kSpriteVS), nullptr, &g.vs);
    if (FAILED(hr)) { log::Write(log::Level::Error, "GFX: CreateVertexShader failed (0x%08lx)", hr); return false; }
    hr = g.device->CreatePixelShader(kSpritePS, sizeof(kSpritePS), nullptr, &g.ps);
    if (FAILED(hr)) { log::Write(log::Level::Error, "GFX: CreatePixelShader failed (0x%08lx)", hr); return false; }

    const D3D11_INPUT_ELEMENT_DESC elems[3] = {
        {"POSITION", 0, DXGI_FORMAT_R32G32_FLOAT,   0, 0,  D3D11_INPUT_PER_VERTEX_DATA, 0},
        {"TEXCOORD", 0, DXGI_FORMAT_R32G32_FLOAT,   0, 8,  D3D11_INPUT_PER_VERTEX_DATA, 0},
        {"COLOR",    0, DXGI_FORMAT_R8G8B8A8_UNORM, 0, 16, D3D11_INPUT_PER_VERTEX_DATA, 0},
    };
    hr = g.device->CreateInputLayout(elems, 3, kSpriteVS, sizeof(kSpriteVS), &g.layout);
    if (FAILED(hr)) { return false; }

    D3D11_BUFFER_DESC vb {};
    vb.ByteWidth      = static_cast<UINT>(sizeof(Vertex) * kMaxVertices);
    vb.Usage          = D3D11_USAGE_DYNAMIC;
    vb.BindFlags      = D3D11_BIND_VERTEX_BUFFER;
    vb.CPUAccessFlags = D3D11_CPU_ACCESS_WRITE;
    hr = g.device->CreateBuffer(&vb, nullptr, &g.vbuf);
    if (FAILED(hr)) { return false; }

    D3D11_BUFFER_DESC cb {};
    cb.ByteWidth      = 64;   // one float4x4
    cb.Usage          = D3D11_USAGE_DYNAMIC;
    cb.BindFlags      = D3D11_BIND_CONSTANT_BUFFER;
    cb.CPUAccessFlags = D3D11_CPU_ACCESS_WRITE;
    hr = g.device->CreateBuffer(&cb, nullptr, &g.cbuf);
    if (FAILED(hr)) { return false; }

    D3D11_BLEND_DESC bd {};   // straight alpha, as raylib
    bd.RenderTarget[0].BlendEnable           = TRUE;
    bd.RenderTarget[0].SrcBlend              = D3D11_BLEND_SRC_ALPHA;
    bd.RenderTarget[0].DestBlend             = D3D11_BLEND_INV_SRC_ALPHA;
    bd.RenderTarget[0].BlendOp               = D3D11_BLEND_OP_ADD;
    bd.RenderTarget[0].SrcBlendAlpha         = D3D11_BLEND_ONE;
    bd.RenderTarget[0].DestBlendAlpha        = D3D11_BLEND_INV_SRC_ALPHA;
    bd.RenderTarget[0].BlendOpAlpha          = D3D11_BLEND_OP_ADD;
    bd.RenderTarget[0].RenderTargetWriteMask = D3D11_COLOR_WRITE_ENABLE_ALL;
    hr = g.device->CreateBlendState(&bd, &g.blend);
    if (FAILED(hr)) { return false; }

    D3D11_RASTERIZER_DESC rd {};
    rd.FillMode        = D3D11_FILL_SOLID;
    rd.CullMode        = D3D11_CULL_NONE;
    rd.DepthClipEnable = TRUE;
    hr = g.device->CreateRasterizerState(&rd, &g.raster);
    return SUCCEEDED(hr);
}

bool CreateSamplers()
{
    const D3D11_FILTER filters[kFilters] = {D3D11_FILTER_MIN_MAG_MIP_POINT, D3D11_FILTER_MIN_MAG_LINEAR_MIP_POINT, D3D11_FILTER_MIN_MAG_MIP_LINEAR};
    const D3D11_TEXTURE_ADDRESS_MODE wraps[kWraps] = {D3D11_TEXTURE_ADDRESS_CLAMP, D3D11_TEXTURE_ADDRESS_WRAP};
    for (int f = 0; f < kFilters; ++f) {
        for (int w = 0; w < kWraps; ++w) {
            D3D11_SAMPLER_DESC sd {};
            sd.Filter         = filters[f];
            sd.AddressU       = wraps[w];
            sd.AddressV       = wraps[w];
            sd.AddressW       = wraps[w];
            sd.ComparisonFunc = D3D11_COMPARISON_NEVER;
            sd.MaxLOD         = D3D11_FLOAT32_MAX;
            const HRESULT hr = g.device->CreateSamplerState(&sd, &g.samplers[static_cast<size_t>(f)][static_cast<size_t>(w)]);
            if (FAILED(hr)) { return false; }
        }
    }
    return true;
}

void BindPipeline()
{
    const UINT stride = sizeof(Vertex), offset = 0;
    ID3D11Buffer* vb = g.vbuf.Get();
    ID3D11Buffer* cb = g.cbuf.Get();
    g.ctx->IASetInputLayout(g.layout.Get());
    g.ctx->IASetPrimitiveTopology(D3D11_PRIMITIVE_TOPOLOGY_TRIANGLELIST);
    g.ctx->IASetVertexBuffers(0, 1, &vb, &stride, &offset);
    g.ctx->VSSetShader(g.vs.Get(), nullptr, 0);
    g.ctx->VSSetConstantBuffers(0, 1, &cb);
    g.ctx->PSSetShader(g.ps.Get(), nullptr, 0);
    g.ctx->OMSetBlendState(g.blend.Get(), nullptr, 0xFFFFFFFFu);
    g.ctx->RSSetState(g.raster.Get());
}

// Pixels -> clip space with the camera folded in: x' = (2z/W) x + (2ox/W - 1), y' = -(2z/H) y + (1 - 2oy/H).
void UpdateProjection()
{
    assert(g.curW > 0 && g.curH > 0);
    const float W = static_cast<float>(g.curW), H = static_cast<float>(g.curH), z = g.viewZoom;
    const float m[16] = {
        2.0f * z / W, 0.0f,          0.0f, 2.0f * g.viewOffset.x / W - 1.0f,
        0.0f,         -2.0f * z / H, 0.0f, 1.0f - 2.0f * g.viewOffset.y / H,
        0.0f,         0.0f,          1.0f, 0.0f,
        0.0f,         0.0f,          0.0f, 1.0f,
    };
    D3D11_MAPPED_SUBRESOURCE map {};
    if (SUCCEEDED(g.ctx->Map(g.cbuf.Get(), 0, D3D11_MAP_WRITE_DISCARD, 0, &map))) {
        std::memcpy(map.pData, m, sizeof(m));
        g.ctx->Unmap(g.cbuf.Get(), 0);
    }
}

void SetCurrentTarget(ID3D11RenderTargetView* rtv, int w, int h)
{
    assert(rtv != nullptr && w > 0 && h > 0);
    ID3D11ShaderResourceView* nullSrv = nullptr;
    g.ctx->PSSetShaderResources(0, 1, &nullSrv);   // a target's texture may have been the last thing sampled
    g.ctx->OMSetRenderTargets(1, &rtv, nullptr);
    D3D11_VIEWPORT vp {0.0f, 0.0f, static_cast<float>(w), static_cast<float>(h), 0.0f, 1.0f};
    g.ctx->RSSetViewports(1, &vp);
    g.curRtv = rtv;
    g.curW   = w;
    g.curH   = h;
    UpdateProjection();
}

void ResizeSwapChain(int w, int h)
{
    assert(w > 0 && h > 0);
    draw::Flush();
    g.ctx->OMSetRenderTargets(0, nullptr, nullptr);
    g.backRtv.Reset();
    const HRESULT hr = g.swap->ResizeBuffers(0, static_cast<UINT>(w), static_cast<UINT>(h), DXGI_FORMAT_UNKNOWN, 0);
    if (FAILED(hr)) { log::Write(log::Level::Error, "GFX: ResizeBuffers failed (0x%08lx)", hr); return; }
    if (CreateBackBufferView()) {
        g.backW = w;
        g.backH = h;
    }
}

// With the debug layer (Debug builds, when the Graphics Tools feature is
// installed) Direct3D records why it disliked a call. Print the last few.
void DumpDebugMessages()
{
    ComPtr<ID3D11InfoQueue> queue;
    if (!g.device || FAILED(g.device.As(&queue))) { log::Write(log::Level::Info, "GFX: no debug layer; build Debug with Graphics Tools installed for details"); return; }
    const UINT64 count = queue->GetNumStoredMessages();
    const UINT64 first = (count > 32) ? count - 32 : 0;
    for (UINT64 i = first; i < count; ++i) {
        SIZE_T len = 0;
        // Spelled GetMessage on purpose: on the desktop winuser.h's macro renames
        // both this call and the interface method to GetMessageW; UWP has no such macro.
        if (FAILED(queue->GetMessage(i, nullptr, &len)) || len == 0 || len > 4096) { continue; }
        alignas(D3D11_MESSAGE) unsigned char buf[4096] = {0};
        D3D11_MESSAGE* msg = reinterpret_cast<D3D11_MESSAGE*>(buf);
        if (SUCCEEDED(queue->GetMessage(i, msg, &len))) {
            log::Write(log::Level::Warning, "D3D11: %.*s", static_cast<int>(msg->DescriptionByteLength), msg->pDescription);
        }
    }
}

int FreeTextureSlot()
{
    for (int i = 0; i < gfx::kMaxTextures; ++i) {
        if (!g.textures[static_cast<size_t>(i)].used) { return i; }
    }
    return -1;
}

// ---- batch -----------------------------------------------------------------

void PushTriangle(TextureId tex, const Vertex& a, const Vertex& b, const Vertex& c)
{
    assert(ValidTexture(tex));
    if (tex.index != g.batchTex.index || g.vertCount + 3 > kMaxVertices) { draw::Flush(); }
    g.batchTex = tex;
    g.verts[static_cast<size_t>(g.vertCount)]     = a;
    g.verts[static_cast<size_t>(g.vertCount + 1)] = b;
    g.verts[static_cast<size_t>(g.vertCount + 2)] = c;
    g.vertCount += 3;
    assert(g.vertCount <= kMaxVertices);
}

Vertex V(float x, float y, float u, float v, unsigned int rgba)
{
    return Vertex {x, y, u, v, rgba};
}

// Solid-colour triangle on the white texture.
void PushSolid(Vector2 a, Vector2 b, Vector2 c, Color col)
{
    const unsigned int p = Pack(col);
    PushTriangle(g.white, V(a.x, a.y, 0.5f, 0.5f, p), V(b.x, b.y, 0.5f, 0.5f, p), V(c.x, c.y, 0.5f, 0.5f, p));
}

} // namespace

// ============================================================================
// gfx
// ============================================================================

namespace gfx {

bool Init()
{
    assert(!g.ready);
    HWND hwnd = static_cast<HWND>(platform::NativeWindow());
    assert(hwnd != nullptr);
    g.backW = platform::Width();
    g.backH = platform::Height();

    const D3D_FEATURE_LEVEL levels[3] = {D3D_FEATURE_LEVEL_11_0, D3D_FEATURE_LEVEL_10_1, D3D_FEATURE_LEVEL_10_0};
    D3D_FEATURE_LEVEL got = D3D_FEATURE_LEVEL_10_0;
    UINT flags = 0;
#if defined(_DEBUG)
    flags |= D3D11_CREATE_DEVICE_DEBUG;
#endif
    HRESULT hr = D3D11CreateDevice(nullptr, D3D_DRIVER_TYPE_HARDWARE, nullptr, flags, levels, 3, D3D11_SDK_VERSION, &g.device, &got, &g.ctx);
    if (FAILED(hr) && (flags & D3D11_CREATE_DEVICE_DEBUG) != 0) {   // no debug layer installed: try without
        hr = D3D11CreateDevice(nullptr, D3D_DRIVER_TYPE_HARDWARE, nullptr, 0, levels, 3, D3D11_SDK_VERSION, &g.device, &got, &g.ctx);
    }
    if (FAILED(hr)) { log::Write(log::Level::Error, "GFX: D3D11CreateDevice failed (0x%08lx)", hr); return false; }

    // The swap chain comes from the DXGI factory that owns the device's adapter.
    // Only the window handoff differs between the PC (HWND) and UWP (CoreWindow).
    ComPtr<IDXGIDevice1>  dxgiDevice;
    ComPtr<IDXGIAdapter>  adapter;
    ComPtr<IDXGIFactory2> factory;
    if (FAILED(g.device.As(&dxgiDevice)) || FAILED(dxgiDevice->GetAdapter(&adapter)) || FAILED(adapter->GetParent(IID_PPV_ARGS(&factory)))) {
        log::Write(log::Level::Error, "GFX: could not reach the DXGI factory");
        return false;
    }
    DXGI_SWAP_CHAIN_DESC1 sd {};
    sd.Width            = static_cast<UINT>(g.backW);
    sd.Height           = static_cast<UINT>(g.backH);
    sd.Format           = DXGI_FORMAT_R8G8B8A8_UNORM;
    sd.SampleDesc.Count = 1;
    sd.BufferUsage      = DXGI_USAGE_RENDER_TARGET_OUTPUT;
    sd.BufferCount      = 2;
    sd.SwapEffect       = DXGI_SWAP_EFFECT_FLIP_DISCARD;
    sd.AlphaMode        = DXGI_ALPHA_MODE_IGNORE;
#if WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_DESKTOP)
    sd.Scaling = DXGI_SCALING_NONE;
    hr = factory->CreateSwapChainForHwnd(g.device.Get(), hwnd, &sd, nullptr, nullptr, &g.swap);
    if (SUCCEEDED(hr)) { (void)factory->MakeWindowAssociation(hwnd, DXGI_MWA_NO_ALT_ENTER); }
#else
    sd.Scaling = DXGI_SCALING_STRETCH;   // CoreWindow swap chains must stretch
    (void)hwnd;
    hr = factory->CreateSwapChainForCoreWindow(g.device.Get(), static_cast<IUnknown*>(platform::NativeWindow()), &sd, nullptr, &g.swap);
#endif
    if (FAILED(hr)) { log::Write(log::Level::Error, "GFX: swap chain failed (0x%08lx)", hr); return false; }
    log::Write(log::Level::Info, "GFX: Direct3D feature level 0x%x, back buffer %d x %d", static_cast<unsigned>(got), g.backW, g.backH);

    if (!CreateBackBufferView() || !CreatePipeline() || !CreateSamplers()) { return false; }

    const Color white {255, 255, 255, 255};
    g.white = CreateTexture(1, 1, &white, false);
    g.ready = ValidTexture(g.white);
    assert(g.ready);

    // Bind everything now, not per frame: raylib-style code draws into a
    // render target before BeginFrame, and Direct3D draws nothing without a
    // bound shader and topology (with the debug layer, it removes the device).
    BindPipeline();
    SetCurrentTarget(g.backRtv.Get(), g.backW, g.backH);
    return g.ready;
}

void Shutdown()
{
    if (g.ctx) { g.ctx->ClearState(); }
    g = State {};
}

void Trim()
{
    if (!g.device) { return; }
    draw::Flush();
    ComPtr<IDXGIDevice3> dxgi;
    if (SUCCEEDED(g.device.As(&dxgi))) { dxgi->Trim(); }
}

void BeginFrame()
{
    assert(g.ready);
    const int w = platform::Width(), h = platform::Height();
    if ((w != g.backW || h != g.backH) && w > 0 && h > 0) { ResizeSwapChain(w, h); }
    BindPipeline();
    g.viewOffset  = Vector2 {0.0f, 0.0f};
    g.viewZoom    = 1.0f;
    g.boundTarget = TargetId {};
    SetCurrentTarget(g.backRtv.Get(), g.backW, g.backH);
}

void EndFrame()
{
    assert(g.ready);
    if (g.boundTarget.Valid()) { EndTarget(); }
    draw::Flush();
    const HRESULT hr = g.swap->Present(1, 0);
    if (hr == DXGI_ERROR_DEVICE_REMOVED || hr == DXGI_ERROR_DEVICE_RESET) {
        log::Write(log::Level::Error, "GFX: device lost (0x%08lx, reason 0x%08lx); closing", hr, g.device->GetDeviceRemovedReason());
        DumpDebugMessages();
        platform::RequestClose();
    }
}

void Clear(Color c)
{
    assert(g.curRtv != nullptr);
    draw::Flush();
    const float rgba[4] = {c.r / 255.0f, c.g / 255.0f, c.b / 255.0f, c.a / 255.0f};
    g.ctx->ClearRenderTargetView(g.curRtv, rgba);
}

int BackBufferWidth()  { return g.backW; }
int BackBufferHeight() { return g.backH; }

TextureId CreateTexture(int width, int height, const Color* pixels, bool mipmaps)
{
    assert(width > 0 && height > 0);
    const int slot = FreeTextureSlot();
    if (slot < 0) { log::Write(log::Level::Warning, "GFX: texture table full (%d)", kMaxTextures); return TextureId {}; }

    D3D11_TEXTURE2D_DESC td {};
    td.Width            = static_cast<UINT>(width);
    td.Height           = static_cast<UINT>(height);
    td.MipLevels        = mipmaps ? 0u : 1u;   // 0 = full chain
    td.ArraySize        = 1;
    td.Format           = DXGI_FORMAT_R8G8B8A8_UNORM;
    td.SampleDesc.Count = 1;
    td.Usage            = D3D11_USAGE_DEFAULT;
    td.BindFlags        = D3D11_BIND_SHADER_RESOURCE | (mipmaps ? D3D11_BIND_RENDER_TARGET : 0u);
    td.MiscFlags        = mipmaps ? D3D11_RESOURCE_MISC_GENERATE_MIPS : 0u;

    TextureSlot& t = g.textures[static_cast<size_t>(slot)];
    const UINT pitch = static_cast<UINT>(width) * 4u;
    HRESULT hr = S_OK;
    if (!mipmaps && pixels != nullptr) {
        D3D11_SUBRESOURCE_DATA init {pixels, pitch, 0};
        hr = g.device->CreateTexture2D(&td, &init, &t.tex);
    } else {
        hr = g.device->CreateTexture2D(&td, nullptr, &t.tex);
        if (SUCCEEDED(hr) && pixels != nullptr) { g.ctx->UpdateSubresource(t.tex.Get(), 0, nullptr, pixels, pitch, 0); }
    }
    if (SUCCEEDED(hr)) { hr = g.device->CreateShaderResourceView(t.tex.Get(), nullptr, &t.srv); }
    if (FAILED(hr)) {
        log::Write(log::Level::Error, "GFX: texture %d x %d failed (0x%08lx)", width, height, hr);
        t = TextureSlot {};
        return TextureId {};
    }
    if (mipmaps && pixels != nullptr) { g.ctx->GenerateMips(t.srv.Get()); }
    t.w = width; t.h = height; t.used = true; t.isTarget = false;
    t.filter = Filter::Point; t.wrap = Wrap::Clamp;
    return TextureId {slot};
}

void DestroyTexture(TextureId id)
{
    if (!ValidTexture(id)) { return; }
    draw::Flush();
    g.textures[static_cast<size_t>(id.index)] = TextureSlot {};
}

bool TextureValid(TextureId id)      { return ValidTexture(id); }
int  TextureWidth(TextureId id)      { return ValidTexture(id) ? Tex(id).w : 0; }
int  TextureHeight(TextureId id)     { return ValidTexture(id) ? Tex(id).h : 0; }
bool TextureIsTarget(TextureId id)   { return ValidTexture(id) && Tex(id).isTarget; }
TextureId WhiteTexture()             { return g.white; }

void SetTextureFilter(TextureId id, Filter f)
{
    if (!ValidTexture(id)) { return; }
    draw::Flush();
    Tex(id).filter = f;
}

void SetTextureWrap(TextureId id, Wrap w)
{
    if (!ValidTexture(id)) { return; }
    draw::Flush();
    Tex(id).wrap = w;
}

TargetId CreateTarget(int width, int height)
{
    assert(width > 0 && height > 0);
    int slot = -1;
    for (int i = 0; i < kMaxTargets && slot < 0; ++i) { if (!g.targets[static_cast<size_t>(i)].used) { slot = i; } }
    const int texSlot = FreeTextureSlot();
    if (slot < 0 || texSlot < 0) { log::Write(log::Level::Warning, "GFX: no free render target or texture slot"); return TargetId {}; }

    D3D11_TEXTURE2D_DESC td {};
    td.Width = static_cast<UINT>(width); td.Height = static_cast<UINT>(height);
    td.MipLevels = 1; td.ArraySize = 1;
    td.Format = DXGI_FORMAT_R8G8B8A8_UNORM; td.SampleDesc.Count = 1;
    td.Usage = D3D11_USAGE_DEFAULT;
    td.BindFlags = D3D11_BIND_RENDER_TARGET | D3D11_BIND_SHADER_RESOURCE;

    TextureSlot& t = g.textures[static_cast<size_t>(texSlot)];
    TargetSlot&  r = g.targets[static_cast<size_t>(slot)];
    HRESULT hr = g.device->CreateTexture2D(&td, nullptr, &t.tex);
    if (SUCCEEDED(hr)) { hr = g.device->CreateShaderResourceView(t.tex.Get(), nullptr, &t.srv); }
    if (SUCCEEDED(hr)) { hr = g.device->CreateRenderTargetView(t.tex.Get(), nullptr, &r.rtv); }
    if (FAILED(hr)) {
        log::Write(log::Level::Error, "GFX: render target %d x %d failed (0x%08lx)", width, height, hr);
        t = TextureSlot {}; r = TargetSlot {};
        return TargetId {};
    }
    t.w = width; t.h = height; t.used = true; t.isTarget = true; t.filter = Filter::Point; t.wrap = Wrap::Clamp;
    r.texture = TextureId {texSlot}; r.w = width; r.h = height; r.used = true;
    return TargetId {slot};
}

void DestroyTarget(TargetId id)
{
    if (!ValidTarget(id)) { return; }
    if (g.boundTarget.index == id.index) { EndTarget(); }
    TargetSlot& r = g.targets[static_cast<size_t>(id.index)];
    DestroyTexture(r.texture);
    r = TargetSlot {};
}

bool      TargetValid(TargetId id)   { return ValidTarget(id); }
TextureId TargetTexture(TargetId id) { return ValidTarget(id) ? g.targets[static_cast<size_t>(id.index)].texture : TextureId {}; }

void BeginTarget(TargetId id)
{
    assert(ValidTarget(id) && !g.boundTarget.Valid());
    if (!ValidTarget(id)) { return; }
    draw::Flush();
    const TargetSlot& r = g.targets[static_cast<size_t>(id.index)];
    SetCurrentTarget(r.rtv.Get(), r.w, r.h);
    g.boundTarget = id;
}

void EndTarget()
{
    if (!g.boundTarget.Valid()) { return; }
    draw::Flush();
    g.boundTarget = TargetId {};
    SetCurrentTarget(g.backRtv.Get(), g.backW, g.backH);
}

} // namespace gfx

// ============================================================================
// draw
// ============================================================================

namespace draw {

void SetView(Vector2 offset, float zoom)
{
    assert(zoom > 0.0f);
    Flush();
    g.viewOffset = offset;
    g.viewZoom   = zoom;
    UpdateProjection();
}

void Flush()
{
    if (g.vertCount == 0) { return; }
    assert(ValidTexture(g.batchTex));
    D3D11_MAPPED_SUBRESOURCE map {};
    if (FAILED(g.ctx->Map(g.vbuf.Get(), 0, D3D11_MAP_WRITE_DISCARD, 0, &map))) { g.vertCount = 0; return; }
    std::memcpy(map.pData, g.verts.data(), sizeof(Vertex) * static_cast<size_t>(g.vertCount));
    g.ctx->Unmap(g.vbuf.Get(), 0);

    const TextureSlot& t = Tex(g.batchTex);
    ID3D11ShaderResourceView* srv = t.srv.Get();
    ID3D11SamplerState* smp = g.samplers[static_cast<size_t>(t.filter)][static_cast<size_t>(t.wrap)].Get();
    g.ctx->PSSetShaderResources(0, 1, &srv);
    g.ctx->PSSetSamplers(0, 1, &smp);
    g.ctx->Draw(static_cast<UINT>(g.vertCount), 0);
    g.vertCount = 0;
}

void Quad(TextureId tex, Rectangle src, Rectangle dst, Vector2 origin, float rotationDeg, Color tint)
{
    if (!ValidTexture(tex)) { return; }
    const TextureSlot& t = Tex(tex);
    const float tw = static_cast<float>(t.w), th = static_cast<float>(t.h);

    // Negative source extents flip that axis (raylib semantics).
    const bool  flipX = src.width < 0.0f, flipY = src.height < 0.0f;
    const float sw = std::fabs(src.width), sh = std::fabs(src.height);
    float u0 = src.x / tw, u1 = (src.x + sw) / tw;
    float v0 = src.y / th, v1 = (src.y + sh) / th;
    if (flipX) { const float t2 = u0; u0 = u1; u1 = t2; }
    if (flipY) { const float t2 = v0; v0 = v1; v1 = t2; }

    // Corners relative to the origin point, rotated about it, placed at dst.x/y.
    const float dx = -origin.x, dy = -origin.y;
    Vector2 tl, tr, bl, br;
    if (rotationDeg == 0.0f) {
        tl = Vector2 {dst.x + dx, dst.y + dy};
        tr = Vector2 {tl.x + dst.width, tl.y};
        bl = Vector2 {tl.x, tl.y + dst.height};
        br = Vector2 {tl.x + dst.width, tl.y + dst.height};
    } else {
        const float rad = rotationDeg * kPi / 180.0f, s = std::sin(rad), c = std::cos(rad);
        const float x2 = dx + dst.width, y2 = dy + dst.height;
        tl = Vector2 {dst.x + dx * c - dy * s, dst.y + dx * s + dy * c};
        tr = Vector2 {dst.x + x2 * c - dy * s, dst.y + x2 * s + dy * c};
        bl = Vector2 {dst.x + dx * c - y2 * s, dst.y + dx * s + y2 * c};
        br = Vector2 {dst.x + x2 * c - y2 * s, dst.y + x2 * s + y2 * c};
    }
    const unsigned int p = Pack(tint);
    PushTriangle(tex, V(tl.x, tl.y, u0, v0, p), V(tr.x, tr.y, u1, v0, p), V(br.x, br.y, u1, v1, p));
    PushTriangle(tex, V(tl.x, tl.y, u0, v0, p), V(br.x, br.y, u1, v1, p), V(bl.x, bl.y, u0, v1, p));
}

void Rect(Rectangle r, Color c)
{
    Quad(g.white, Rectangle {0.0f, 0.0f, 1.0f, 1.0f}, r, Vector2 {0.0f, 0.0f}, 0.0f, c);
}

void RectGradientH(Rectangle r, Color left, Color right)
{
    const unsigned int l = Pack(left), rt = Pack(right);
    const float x1 = r.x + r.width, y1 = r.y + r.height;
    PushTriangle(g.white, V(r.x, r.y, 0.5f, 0.5f, l), V(x1, r.y, 0.5f, 0.5f, rt), V(x1, y1, 0.5f, 0.5f, rt));
    PushTriangle(g.white, V(r.x, r.y, 0.5f, 0.5f, l), V(x1, y1, 0.5f, 0.5f, rt), V(r.x, y1, 0.5f, 0.5f, l));
}

void RectLines(Rectangle r, float thick, Color c)
{
    assert(thick > 0.0f);
    Rect(Rectangle {r.x, r.y, r.width, thick}, c);
    Rect(Rectangle {r.x, r.y + r.height - thick, r.width, thick}, c);
    Rect(Rectangle {r.x, r.y + thick, thick, r.height - 2.0f * thick}, c);
    Rect(Rectangle {r.x + r.width - thick, r.y + thick, thick, r.height - 2.0f * thick}, c);
}

void Triangle(Vector2 a, Vector2 b, Vector2 c, Color col)
{
    PushSolid(a, b, c, col);
}

void Line(Vector2 a, Vector2 b, float thick, Color c)
{
    assert(thick > 0.0f);
    const float dx = b.x - a.x, dy = b.y - a.y;
    const float len = std::sqrt(dx * dx + dy * dy);
    if (len <= 0.0f) { return; }
    const float nx = -dy / len * thick * 0.5f, ny = dx / len * thick * 0.5f;
    PushSolid(Vector2 {a.x + nx, a.y + ny}, Vector2 {b.x + nx, b.y + ny}, Vector2 {b.x - nx, b.y - ny}, c);
    PushSolid(Vector2 {a.x + nx, a.y + ny}, Vector2 {b.x - nx, b.y - ny}, Vector2 {a.x - nx, a.y - ny}, c);
}

void CircleSector(Vector2 centre, float radius, float startDeg, float endDeg, int segments, Color c)
{
    assert(radius >= 0.0f);
    if (segments < 4) { segments = 4; }
    if (segments > 360) { segments = 360; }
    const float step = (endDeg - startDeg) / static_cast<float>(segments) * kPi / 180.0f;
    float ang = startDeg * kPi / 180.0f;
    for (int i = 0; i < segments; ++i) {
        const Vector2 p0 {centre.x + std::cos(ang) * radius, centre.y + std::sin(ang) * radius};
        const Vector2 p1 {centre.x + std::cos(ang + step) * radius, centre.y + std::sin(ang + step) * radius};
        PushSolid(centre, p0, p1, c);
        ang += step;
    }
}

void Circle(Vector2 centre, float radius, Color c)
{
    CircleSector(centre, radius, 0.0f, 360.0f, kCircleSegments, c);
}

void CircleLines(Vector2 centre, float radius, Color c)
{
    assert(radius >= 0.0f);
    const float step = 2.0f * kPi / static_cast<float>(kCircleSegments);
    for (int i = 0; i < kCircleSegments; ++i) {
        const float a0 = step * static_cast<float>(i), a1 = a0 + step;
        Line(Vector2 {centre.x + std::cos(a0) * radius, centre.y + std::sin(a0) * radius},
             Vector2 {centre.x + std::cos(a1) * radius, centre.y + std::sin(a1) * radius}, 1.0f, c);
    }
}

void Ellipse(Vector2 centre, float rx, float ry, Color c)
{
    assert(rx >= 0.0f && ry >= 0.0f);
    const float step = 2.0f * kPi / static_cast<float>(kCircleSegments);
    for (int i = 0; i < kCircleSegments; ++i) {
        const float a0 = step * static_cast<float>(i), a1 = a0 + step;
        PushSolid(centre, Vector2 {centre.x + std::cos(a0) * rx, centre.y + std::sin(a0) * ry},
                  Vector2 {centre.x + std::cos(a1) * rx, centre.y + std::sin(a1) * ry}, c);
    }
}

} // namespace draw

} // namespace rf
